# Changes here will be overwritten by Copier
_commit: v3.6.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: sairangareddy22@gmail.com
author_name: Ranga Reddy Nukala
github_page: ''
project_description: Import dataset resources from Kaggle.
project_slug: kaggle
pypi: false

