---
default:
  image: docker-registry.eccenca.com/eccenca-python:v3.9.16
  # all jobs can be interrupted in case a new commit is pushed
  interruptible: true
  before_script:
    # make sure poetry creates virtual environment as .venv
    - poetry config virtualenvs.in-project true
  cache:
    # cache the virtual environment based on the poetry lock file
    key:
      files:
        - poetry.lock
    paths:
      - .venv

stages:
  - test
  - build

check:
  stage: test
  script:
    - task check
  artifacts:
    when: always
    reports:
      cobertura:
        - ./dist/coverage.xml
      junit:
        - ./dist/junit-bandit.xml
        - ./dist/junit-flake8.xml
        - ./dist/junit-mypy.xml
        - ./dist/junit-pylint.xml
        - ./dist/junit-pytest.xml
    paths:
      - ./dist/badge-coverage.svg
      - ./dist/badge-tests.svg
      - ./dist/coverage
      - ./dist/coverage.xml

build:
  stage: build
  script:
    - task build
  artifacts:
    when: always
    paths:
      - ./dist/*.tar.gz
      - ./dist/*.whl

